#!/bin/bash

#BACKUPS_DESTINATION="/data-hdd/backups"
BACKUPS_DESTINATION="/data-hdd2/backups"

# format:
# rsync -a --delete --quiet /path/to/backup /location/of/backup

# stop the script if an error occurs
set -e

rsync -a --delete --quiet --exclude="{"/home/*/.cache/*"}" /home/mischa $BACKUPS_DESTINATION/home
rsync -a --delete --quiet /etc $BACKUPS_DESTINATION

echo "Made backups on: $(date)" >> /var/log/backup.log

#rsync -a --delete --info=stats1,progress2 --exclude={"/home/*/.cache/*"} /home/mischa /data-hdd2/backups/home
